//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PSO2Utility.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PSO2Utility.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   PSO2 has already started. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AlreadyStarted {
            get {
                return ResourceManager.GetString("AlreadyStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A&amp;uto Start PSO2 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AutoExecuteGame {
            get {
                return ResourceManager.GetString("AutoExecuteGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &amp;Auto Restore Window Position に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AutoRestoreWindowPosition {
            get {
                return ResourceManager.GetString("AutoRestoreWindowPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Folder not found. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DirectoryNotFound {
            get {
                return ResourceManager.GetString("DirectoryNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &amp;Start PSO2 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ExecuteGame {
            get {
                return ResourceManager.GetString("ExecuteGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Execution failed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ExecutionFailed {
            get {
                return ResourceManager.GetString("ExecutionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   E&amp;xit に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File not found. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FileNotFound {
            get {
                return ResourceManager.GetString("FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open &amp;Log Folder に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string OpenLogFolder {
            get {
                return ResourceManager.GetString("OpenLogFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open Scr&amp;eenshot Folder に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string OpenScreenshotFolder {
            get {
                return ResourceManager.GetString("OpenScreenshotFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &amp;Options に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Options {
            get {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Set the option &quot;Folder of PSO2&quot; required for this operation. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string RequireOptionGameFolder {
            get {
                return ResourceManager.GetString("RequireOptionGameFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &amp;Restore Window Position に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string RestoreWindowPosition {
            get {
                return ResourceManager.GetString("RestoreWindowPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sa&amp;ve Window Position に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SaveWindowPosition {
            get {
                return ResourceManager.GetString("SaveWindowPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show Minimize &amp;Button に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShowSystemButtons {
            get {
                return ResourceManager.GetString("ShowSystemButtons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Window not found. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WindowNotFound {
            get {
                return ResourceManager.GetString("WindowNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Window operation failed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WindowOperationFailed {
            get {
                return ResourceManager.GetString("WindowOperationFailed", resourceCulture);
            }
        }
    }
}
